#!/usr/bin/env Rscript
#
# Regenerates tests/testthat/test-spectrum.R from csv-spectrum, the de facto
# acid test for CSV parsers (https://github.com/max-mapper/csv-spectrum,
# BSD-2-Clause).
#
#   Rscript tools/update-csv-spectrum.R [commit-ish]
#
# The fixtures are transcribed into the test as raw byte vectors rather than
# vendored as files, for one specific reason: upstream keeps the CRLF
# fixtures correct with `.gitattributes` (`csvs/*_crlf.csv eol=crlf`), so
# copying the files in would make our CRLF coverage depend on every future
# checkout of *this* repo honouring a line-ending rule. Raw bytes in an R
# file cannot be normalised by git, by an editor, or by a Windows clone --
# which is the same reason the rest of the suite writes its fixtures with
# writeBin().
#
# Needs jsonlite and git, at development time only. Neither is a package
# dependency: the generated test is self-contained and reads no JSON.

args <- commandArgs(trailingOnly = TRUE)
commitish <- if (length(args)) args[[1]] else "master"
repo <- "https://github.com/max-mapper/csv-spectrum.git"

stopifnot(requireNamespace("jsonlite", quietly = TRUE))
work <- tempfile("csv-spectrum-"); dir.create(work)
on.exit(unlink(work, recursive = TRUE), add = TRUE)

message("Cloning ", repo)
stopifnot(system2("git", c("clone", "--quiet", repo, shQuote(work))) == 0L)
stopifnot(system2("git", c("-C", shQuote(work), "checkout", "--quiet", commitish)) == 0L)
sha <- trimws(system2("git", c("-C", shQuote(work), "rev-parse", "HEAD"), stdout = TRUE))

# `location_coordinates` is excluded. Its CSV and its own JSON disagree (the
# phone number is 2095257564 in one and 1234567890 in the other), the JSON is
# a bare object where every other fixture is an array, and the CSV has an
# unquoted `"` inside an unquoted field. Three open upstream issues cover it.
# Re-check on update: if they are fixed, drop this.
skip <- "location_coordinates"

csvs <- sort(sub("\\.csv$", "", basename(Sys.glob(file.path(work, "csvs", "*.csv")))))
csvs <- setdiff(csvs, skip)

# Keep the generated file pure ASCII, as the rest of the suite is.
esc <- function(x) {
  vapply(x, function(s) {
    if (is.na(s)) return("NA_character_")
    cp <- utf8ToInt(s)
    out <- vapply(seq_along(cp), function(i) {
      ch <- substr(s, i, i)
      if (cp[i] == 92L) "\\\\"
      else if (ch == "\"") "\\\""
      else if (cp[i] == 10L) "\\n"
      else if (cp[i] == 13L) "\\r"
      else if (cp[i] == 9L) "\\t"
      else if (cp[i] >= 32L && cp[i] < 127L) ch
      else sprintf("\\u%04x", cp[i])
    }, "")
    paste0("\"", paste(out, collapse = ""), "\"")
  }, "")
}

raw_vec <- function(path) {
  b <- readBin(path, "raw", file.size(path))
  if (!length(b)) return("raw(0)")
  hex <- sprintf("0x%02x", as.integer(b))
  lines <- split(hex, ceiling(seq_along(hex) / 12))
  paste0("as.raw(c(\n    ", paste(vapply(lines, paste, "", collapse = ", "),
                                  collapse = ",\n    "), "\n  ))")
}

out <- c(
  "# Generated by tools/update-csv-spectrum.R -- do not edit by hand.",
  "#",
  "# csv-spectrum (https://github.com/max-mapper/csv-spectrum), BSD-2-Clause,",
  paste0("# at commit ", sha, "."),
  "#",
  "# The de facto acid test for CSV parsers. Fixtures are inlined as raw bytes",
  "# so that the CRLF cases cannot be normalised by a checkout, an editor, or",
  "# git's autocrlf -- upstream relies on .gitattributes for that, which would",
  "# not survive being copied into this repo.",
  "#",
  paste0("# ", length(csvs), " of ", length(csvs) + length(skip), " fixtures. ",
         paste(skip, collapse = ", "), " is excluded; see the generator."),
  "",
  "spectrum_case <- function(bytes, expected) {",
  "  path <- tempfile(fileext = \".csv\")",
  "  con <- file(path, \"wb\"); writeBin(bytes, con); close(con)",
  "  got <- read_csv(path, col_types = \"character\", na = NULL)",
  "  expect_identical(names(got), names(expected))",
  "  expect_identical(nrow(got), nrow(expected))",
  "  for (j in seq_along(expected)) {",
  "    expect_identical(got[[j]], expected[[j]], info = names(expected)[j])",
  "  }",
  "}",
  ""
)

for (nm in csvs) {
  want <- jsonlite::fromJSON(file.path(work, "json", paste0(nm, ".json")),
                             simplifyDataFrame = FALSE)
  cols <- names(want[[1]])
  body <- vapply(cols, function(k) {
    vals <- vapply(want, function(row) {
      v <- row[[k]]
      if (is.null(v)) NA_character_ else as.character(v)
    }, "")
    paste0("    ", esc(k), " = c(", paste(esc(vals), collapse = ", "), ")")
  }, "")
  out <- c(out,
    sprintf("test_that(\"csv-spectrum: %s\", {", nm),
    sprintf("  spectrum_case("),
    paste0("    ", gsub("\n", "\n    ", raw_vec(file.path(work, "csvs", paste0(nm, ".csv"))))),
    "    ,",
    "    data.frame(",
    paste(body, collapse = ",\n"),
    "      , stringsAsFactors = FALSE, check.names = FALSE",
    "    )",
    "  )",
    "})",
    "")
}

dest <- file.path("tests", "testthat", "test-spectrum.R")
writeLines(out, dest)
message("Wrote ", dest, " (", length(csvs), " fixtures, upstream ", substr(sha, 1, 8), ")")
