on:
  push:
    branches: [main, master]
    paths-ignore:
      - ".github/badges/coverage.svg"
  pull_request:

name: coverage

jobs:
  coverage:
    uses: pedrobtz/r-actions/.github/workflows/coverage.yml@v1
    permissions:
      contents: write
